version: 2
jobs:
  frontend-test:
    docker:
      - image: circleci/node:11

    working_directory: ~/repo

    steps:
      - checkout
     
      - restore_cache:
          keys:
          - v1-node-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
          - v1-node-dependencies-

      - run:
          name: install node dependencies
          command: |
            yarn install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-node-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}


      - run:
          name: run tests
          command: |
            yarn run lint
            yarn run test

      - store_artifacts:
          path: coverage_js
          destination: coverage_js


  server-test:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ arch }}-{{ checksum "Pipfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pipenv --rm || true
            pipenv install --dev

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ arch }}-{{ checksum "Pipfile.lock" }}
      
      - run:
          name: run tests
          command: |
            pipenv run lint
            pipenv run test

      - store_artifacts:
          path: coverage_py
          destination: coverage_py

workflows:
  version: 2
  build:
    jobs:
      - frontend-test
      - server-test
